import React,{useState} from "react";import{createRoot}from"react-dom/client";import"./styles.css";
const chapters=Array.from({length:18},(_,i)=>({n:i+1,title:["Arjuna Vishada Yoga","Sankhya Yoga","Karma Yoga","Jnana Karma Sannyasa Yoga","Karma Sannyasa Yoga","Dhyana Yoga","Jnana Vijnana Yoga","Akshara Brahma Yoga","Raja Vidya Raja Guhya Yoga","Vibhuti Yoga","Vishvarupa Darshana Yoga","Bhakti Yoga","Kshetra Kshetrajna Vibhaga Yoga","Gunatraya Vibhaga Yoga","Purushottama Yoga","Daivasura Sampad Vibhaga Yoga","Shraddhatraya Vibhaga Yoga","Moksha Sannyasa Yoga"][i]}));
const samples=[{n:"2.47",s:"कर्मण्येवाधिकारस्ते मा फलेषु कदाचन ।",e:"You have a right to action, but not to the fruits of action."},{n:"2.20",s:"न जायते म्रियते वा कदाचिन्",e:"The Self is described as not being born or destroyed."}];
function App(){const[view,setView]=useState("home"),[chat,setChat]=useState([{role:"assistant",text:"Namaste. I can help you explore Hindu spiritual texts, explain passages in simple language, compare teachings across texts, or guide you chapter by chapter."}]),[q,setQ]=useState(""),[selected,setSelected]=useState(null);
const send=()=>{if(!q.trim())return;const x=q.trim();setChat(c=>[...c,{role:"user",text:x},{role:"assistant",text:"I can explain this using the text you are reading. Connect your AI provider in the backend to enable source-grounded answers. For now, choose a text or chapter from the library to explore."}]);setQ("")};
return <div className="app"><aside><div className="logo">ॐ <span>Sanatan Granth</span></div><button className={view==="home"?"active":""} onClick={()=>setView("home")}>⌂ Home</button><button className={view==="library"?"active":""} onClick={()=>setView("library")}>▤ Library</button><button className={view==="chat"?"active":""} onClick={()=>setView("chat")}>✦ Ask Sanatan</button><div className="sideTitle">Texts</div><button onClick={()=>{setView("reader");setSelected("Bhagavad Gita")}}>Bhagavad Gita</button><button>Upanishads</button><button>Vedas</button><button>Ramayana</button><button>Mahabharata</button><button>Puranas</button><div className="sideBottom">Ancient texts<br/><span>Simple explanations</span></div></aside><main><header><div><b>{view==="chat"?"Ask Sanatan":view==="reader"?selected:"Sanatan Granth"}</b><small>{view==="chat"?"AI spiritual guide":"Read • Understand • Reflect"}</small></div><button className="new" onClick={()=>setView("chat")}>＋ New question</button></header>{view==="home"&&<Home setView={setView}/>} {view==="library"&&<Library setView={setView} setSelected={setSelected}/>} {view==="reader"&&<Reader selected={selected}/>} {view==="chat"&&<Chat chat={chat} q={q} setQ={setQ} send={send}/>}</main></div>}
function Home({setView}){return <section className="home"><div className="hero"><div className="om">ॐ</div><h1>Explore wisdom.<br/><i>Understand deeply.</i></h1><p>A conversational library for Hindu spiritual texts. Read chapter by chapter, listen, ask questions, and get simple explanations.</p><div className="heroBtns"><button onClick={()=>setView("reader")}>Continue with Bhagavad Gita →</button><button className="ghost" onClick={()=>setView("chat")}>Ask a question</button></div></div><h2>Explore the Granths</h2><div className="cards">{["Bhagavad Gita","Upanishads","Vedas","Ramayana","Mahabharata","Puranas"].map((x,i)=><div className="card" onClick={()=>setView("reader")} key={x}><span>{["गीता","उपनिषद्","वेद","रामायण","महाभारत","पुराण"][i]}</span><h3>{x}</h3><p>{i===0?"18 chapters • shloka-by-shloka":"Collection ready for chapter-wise expansion"}</p></div>)}</div></section>}
function Library({setView,setSelected}){return <section className="page"><h1>Library</h1><p>Choose a tradition text and enter its chapter structure.</p><div className="library">{["Bhagavad Gita","Upanishads","Vedas","Ramayana","Mahabharata","Puranas"].map(x=><div className="libRow" onClick={()=>{setSelected(x);setView("reader")}}><div className="book">ॐ</div><div><b>{x}</b><span>Chapter-wise reading</span></div><strong>→</strong></div>)}</div></section>}
function speak(text){if(!("speechSynthesis" in window))return;window.speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang="hi-IN";u.rate=.9;window.speechSynthesis.speak(u)}
function Reader(){return <section className="page"><div className="readerIntro"><span>BHAGAVAD GITA</span><h1>18 chapters</h1><p>Move through the Gita chapter by chapter. Each passage can later be paired with source-grounded explanations and audio.</p></div><div className="chapterGrid">{chapters.map(c=><div className="chapter" onClick={()=>{}}><small>CHAPTER {c.n}</small><h3>{c.title}</h3><span>Explore chapter →</span></div>)}</div><div className="passages"><h2>Featured passages</h2>{samples.map(x=><article><small>{x.n}</small><div className="sanskrit">{x.s}</div><p>{x.e}</p><button>✦ Explain simply</button><button className="textBtn" onClick={()=>speak(x.s)}>🔊 Listen</button></article>)}</div></section>}
function Chat({chat,q,setQ,send}){return <section className="chat"><div className="chatIntro"><div className="avatar">ॐ</div><h1>Ask Sanatan</h1><p>Ask about a verse, chapter, character, concept, or teaching. Answers should be grounded in the selected source.</p></div><div className="messages">{chat.map((m,i)=><div className={"msg "+m.role}><div className="bubble">{m.text}</div></div>)}</div><div className="composer"><textarea value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();send()}}} placeholder="Ask about the Bhagavad Gita, Upanishads, Vedas..."/><button onClick={send}>↑</button></div><div className="chips"><button onClick={()=>setQ("Explain karma in simple language")}>Explain karma</button><button onClick={()=>setQ("What is the main teaching of the Bhagavad Gita?")}>Main teaching of Gita</button><button onClick={()=>setQ("Explain this verse")}>Explain a verse</button></div></section>}
createRoot(document.getElementById("root")).render(<App/>);